# Catch Async

Utility used to wrap root async functions to avoid uncaught promise errors to go silent.

catchAsync is intented for use in the root-level of an asyncronous chain of
functions, basically avoiding the need of using `try/catch` and risking to leave silent errors in code.

# API Documentation

<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

### Table of Contents

-   [catchAsync](#catchasync)

## catchAsync

[src/index.js:38-51](https://github.com/Narzerus/catch-async/blob/98d18bed97ee9fcba985df9e24996d7fc60c602c/src/index.js#L38-L51 "Source code on GitHub")

Returns an async function wrapped in a try catch function. It
will by default log any error thrown in the async function unless
a handleError function is provided. In that case it will instead
call handleError

**Parameters**

-   `asyncFunction` **[Function](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/function)** 
-   `options` **[Object](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object)?**  (optional, default `{}`)
    -   `options.handleError` **[Function](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/function)?** if this function is provided
        then catchAsync will call it instead of logging the error
    -   `options.logType` **[String](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** determines what logging method
        is used when an error is caught. Can be 'error', 'info', 'log' or 'warn' (optional, default `'error'`)

Returns **[Function](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/function)** Wrapped async function
